### ISSUE TITLE
Accounts, authentication & authorization core feature

### ISSUE THREAD

**Issue by duongdev** [targeek/guru-erp#39]
# Todos

- [x] Clarify feature specs
- [x] Test driven development
- [x] Creating accounts
- [x] Signing in accounts (authentication & authorization)
- [ ] ~Updating accounts (skipped this phase)~
